project_id = "adpnzkvzvjbervzrqhhx"

[functions.check-cpf-availability]
verify_jwt = true

[functions.check-email-exists]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.consultar-cpf]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.sync-unified-data]
verify_jwt = false

[functions.sync-plans]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = true

[functions.reprocess-commissions]
verify_jwt = true

[functions.trigger-deploy]
verify_jwt = true
